apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: task-manager
type: Opaque
stringData:
  DATABASE_URL: jdbc:postgresql://postgres-service:5432/taskmanagerdb
  DATABASE_USERNAME: taskmanager
  DATABASE_PASSWORD: "!@paroladb!@"
  JWT_SECRET: MyVerySecureJWTSecretKeyForProduction2025WithMinimum256Bits

