apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend-service
  namespace: task-manager
spec:
  selector:
    app: task-manager-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

